In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"/home/resmi/Downloads/DataHut_AT_Dm_PriceExtractions_20260616.CSV",sep="|")

In [3]:
df.to_parquet(r"/home/resmi/Downloads/DataHut_AT_Dm_PriceExtractions_20260616.parquet", engine='pyarrow', index=False)

In [4]:
df=pd.read_parquet(r"/home/resmi/Downloads/DataHut_AT_Dm_PriceExtractions_20260616.parquet", engine='pyarrow')

In [ ]:
df

,unique_id,competitor_name,extraction_date,product_name,grammage_quantity,grammage_unit,regular_price,selling_price,price_valid_from,price_per_unit,...,promotion_price,promotion_valid_from,promotion_valid_upto,promotion_description,currency,breadcrumb,pdp_url,region,pack_size,site_shown_uom
0,4059729626592,dm,2026-06-16,Körperspray Juicy Bomb Tropical Drop 110 Mango...,100,ml,3.75,3.75,None,3.75 € je 100 ml,...,NaN,None,NaN,NaN,EUR,Startseite,https://www.dm.at/p/d/3132882/essence-koerpers...,NaN,NaN,100 ml
1,2090000510157,dm,2026-06-16,"Jubiläumsbox 50 Jahre dm Beauty, 1 St",1,stück,5.00,5.00,None,5.00 € je 1 St,...,NaN,None,NaN,NaN,EUR,Startseite > Pflege & Parfum > Geschenksets,https://www.dm.at/p/d/3118985/dm-box-jubilaeum...,NaN,NaN,1 St
2,4059729626431,dm,2026-06-16,Körperspray Juicy Bomb Tropical Drop 106 Lyche...,100,ml,3.75,3.75,None,3.75 € je 100 ml,...,NaN,None,NaN,NaN,EUR,Startseite > Pflege & Parfum > Körperpflege > ...,https://www.dm.at/p/d/3132836/essence-koerpers...,NaN,NaN,100 ml
3,800897280741,dm,2026-06-16,"Körperbutter Shimmer Fat Oil Suga Baddie, 145 ml",145,ml,17.95,17.95,None,12.38 € je 100 ml,...,NaN,None,NaN,NaN,EUR,Startseite > Pflege & Parfum > Körperpflege > ...,https://www.dm.at/p/d/3135176/nyx-professional...,NaN,NaN,145 ml
4,800897281526,dm,2026-06-16,"Bodylotion Fat Oil Suga Baddie, 150 ml",150,ml,11.95,11.95,None,7.97 € je 100 ml,...,NaN,None,NaN,NaN,EUR,Startseite > Pflege & Parfum > Körperpflege > ...,https://www.dm.at/p/d/3135173/nyx-professional...,NaN,NaN,150 ml
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16677,30118874,dm,2026-06-16,"Eyeliner Master Ink Matte, 3 g",3,g,9.95,9.95,16.02.2024,None,...,NaN,16.02.2024,NaN,NaN,EUR,Startseite > Make-up > Augen Make-up > Eyeliner,https://www.dm.at/p/d/1477082/maybelline-new-y...,NaN,NaN,3 g
16678,30101678,dm,2026-06-16,"Mascara The Rocket Volum’ Express, 9,6 ml",9.6,ml,11.95,11.95,27.05.2024,None,...,NaN,27.05.2024,NaN,NaN,EUR,Startseite > Make-up > Augen Make-up > Mascara,https://www.dm.at/p/d/1367430/maybelline-new-y...,NaN,NaN,9.6 ml
16679,30108356,dm,2026-06-16,Mascara The Colossal Go Extreme Volum' Express...,10,ml,9.95,9.95,27.05.2024,None,...,NaN,27.05.2024,NaN,NaN,EUR,Startseite > Make-up > Augen Make-up > Mascara,https://www.dm.at/p/d/1398924/maybelline-new-y...,NaN,NaN,10 ml
16680,30121416,dm,2026-06-16,"Nagellack Super Gel 685 Seductive Red, 12 ml",12,ml,5.95,5.95,01.12.2022,None,...,NaN,01.12.2022,NaN,NaN,EUR,Startseite > Make-up > Nägel > Nagellack,https://www.dm.at/p/d/1449607/manhattan-cosmet...,NaN,NaN,12 ml
16681,30098787,dm,2026-06-16,Mascara The Colossal Volum' Express Smoky Blac...,11,ml,8.95,8.95,27.05.2024,None,...,NaN,27.05.2024,NaN,NaN,EUR,Startseite > Make-up > Augen Make-up > Mascara,https://www.dm.at/p/d/1360779/maybelline-new-y...,NaN,NaN,11 ml

In [5]:
df.to_csv(r"/home/resmi/Downloads/DataHut_AT_Dm_PriceExtractions_20260616.csv", index=False)

In [6]:
df = pd.read_csv((r"/home/resmi/Downloads/DataHut_AT_Dm_PriceExtractions_20260616.CSV"), sep="|")

In [7]:
df

,unique_id,competitor_name,extraction_date,product_name,grammage_quantity,grammage_unit,regular_price,selling_price,price_valid_from,price_per_unit,...,promotion_price,promotion_valid_from,promotion_valid_upto,promotion_description,currency,breadcrumb,pdp_url,region,pack_size,site_shown_uom
0,4059729626592,dm,2026-06-16,Körperspray Juicy Bomb Tropical Drop 110 Mango...,100,ml,3.75,3.75,NaN,3.75 € je 100 ml,...,NaN,NaN,NaN,NaN,EUR,Startseite,https://www.dm.at/p/d/3132882/essence-koerpers...,NaN,NaN,100 ml
1,2090000510157,dm,2026-06-16,"Jubiläumsbox 50 Jahre dm Beauty, 1 St",1,stück,5.00,5.00,NaN,5.00 € je 1 St,...,NaN,NaN,NaN,NaN,EUR,Startseite > Pflege & Parfum > Geschenksets,https://www.dm.at/p/d/3118985/dm-box-jubilaeum...,NaN,NaN,1 St
2,4059729626431,dm,2026-06-16,Körperspray Juicy Bomb Tropical Drop 106 Lyche...,100,ml,3.75,3.75,NaN,3.75 € je 100 ml,...,NaN,NaN,NaN,NaN,EUR,Startseite > Pflege & Parfum > Körperpflege > ...,https://www.dm.at/p/d/3132836/essence-koerpers...,NaN,NaN,100 ml
3,800897280741,dm,2026-06-16,"Körperbutter Shimmer Fat Oil Suga Baddie, 145 ml",145,ml,17.95,17.95,NaN,12.38 € je 100 ml,...,NaN,NaN,NaN,NaN,EUR,Startseite > Pflege & Parfum > Körperpflege > ...,https://www.dm.at/p/d/3135176/nyx-professional...,NaN,NaN,145 ml
4,800897281526,dm,2026-06-16,"Bodylotion Fat Oil Suga Baddie, 150 ml",150,ml,11.95,11.95,NaN,7.97 € je 100 ml,...,NaN,NaN,NaN,NaN,EUR,Startseite > Pflege & Parfum > Körperpflege > ...,https://www.dm.at/p/d/3135173/nyx-professional...,NaN,NaN,150 ml
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16677,30118874,dm,2026-06-16,"Eyeliner Master Ink Matte, 3 g",3,g,9.95,9.95,16.02.2024,NaN,...,NaN,16.02.2024,NaN,NaN,EUR,Startseite > Make-up > Augen Make-up > Eyeliner,https://www.dm.at/p/d/1477082/maybelline-new-y...,NaN,NaN,3 g
16678,30101678,dm,2026-06-16,"Mascara The Rocket Volum’ Express, 9,6 ml",9.6,ml,11.95,11.95,27.05.2024,NaN,...,NaN,27.05.2024,NaN,NaN,EUR,Startseite > Make-up > Augen Make-up > Mascara,https://www.dm.at/p/d/1367430/maybelline-new-y...,NaN,NaN,9.6 ml
16679,30108356,dm,2026-06-16,Mascara The Colossal Go Extreme Volum' Express...,10,ml,9.95,9.95,27.05.2024,NaN,...,NaN,27.05.2024,NaN,NaN,EUR,Startseite > Make-up > Augen Make-up > Mascara,https://www.dm.at/p/d/1398924/maybelline-new-y...,NaN,NaN,10 ml
16680,30121416,dm,2026-06-16,"Nagellack Super Gel 685 Seductive Red, 12 ml",12,ml,5.95,5.95,01.12.2022,NaN,...,NaN,01.12.2022,NaN,NaN,EUR,Startseite > Make-up > Nägel > Nagellack,https://www.dm.at/p/d/1449607/manhattan-cosmet...,NaN,NaN,12 ml
16681,30098787,dm,2026-06-16,Mascara The Colossal Volum' Express Smoky Blac...,11,ml,8.95,8.95,27.05.2024,NaN,...,NaN,27.05.2024,NaN,NaN,EUR,Startseite > Make-up > Augen Make-up > Mascara,https://www.dm.at/p/d/1360779/maybelline-new-y...,NaN,NaN,11 ml