In [3]:
import pandas as pd

In [8]:
pd.read_json(r"/home/resmi/Downloads/sutton_2026_06_05 (1).json", lines=True).to_parquet(r"/home/resmi/Downloads/sutton_2026_06_05 (1).parquet", engine='pyarrow', index=False)

In [14]:
df=pd.read_parquet((r"/home/resmi/Downloads/sutton_2026_06_05 (1).parquet"), engine='pyarrow')

In [16]:
df

,first_name,middle_name,last_name,office_name,title,description,languages,image_url,address,city,state,country,zipcode,office_phone_numbers,agent_phone_numbers,email,website,social,profile_url
0,Yenisleidis,,Infante Morales,groupe sutton - clodem inc.,Affiliated Real Estate Broker,Yenisleidis Infante Morales is a Affiliated Re...,"[French, Spanish]",https://www.sutton.com/storage/agents/api/1224...,9515 Boulevard LaSalle,LaSalle,QC,Canada,H8R2M9,[],[438-371-5960],yeni@sutton.com,https://www.facebook.com/yenisleidis.infantemo...,{'facebook_url': 'https://www.facebook.com/yen...,https://www.sutton.com/ca/agent/yenisleidis-in...
1,Ingrid,,Keen,"Sutton Group - Summit Realty Inc., Brokerage",Sales Representative,Ingrid Keen is a Sales Representative at Sutto...,[],https://www.sutton.com/storage/agents/api/5735...,33 Pearl Street,Mississauga,,Canada,L5M1X1,"[905-407-1828, 905-681-7900, 905-681-8225, 905...",[],ikeen@sutton.com,http://suttonsummit.ca,"{'facebook_url': None, 'twitter_url': None, 'l...",https://www.sutton.com/ca/agent/ingrid-keen-57352
2,Linda,,D'Eon,"Sutton Group - Quantum Realty Inc., Brokerage",Sales Representative,Linda D'Eon is a Sales Representative at Sutto...,[English],https://www.sutton.com/storage/agents/api/1045...,1673 Lakeshore Rd W,MISSISSAUGA,,Canada,L5J1J4,[416-305-5617],[],ldeon@sutton.com,,"{'facebook_url': None, 'twitter_url': None, 'l...",https://www.sutton.com/ca/agent/linda-d'eon-10...
3,Youngho,,Kim,Sutton Group - West Coast Realty,Personal Real Estate Corporation Licensing,Youngho Kim is a Sales Representative at Sutto...,[English],https://www.sutton.com/storage/agents/api/1220...,102 - 403 North Road,Coquitlam,BC,Canada,V3K3V9,[778-231-5329],[],ykim@sutton.com,,"{'facebook_url': None, 'twitter_url': None, 'l...",https://www.sutton.com/ca/agent/youngho-kim-12...
4,Brian,,Power,Sutton Group - West Coast Realty,Sales Representative,Brian Power is a Sales Representative at Sutto...,[English],https://www.sutton.com/storage/agents/api/6153...,102 - 403 North Road,Coquitlam,,Canada,V3K3V9,"[604-415-9800, 604-671-4393, 604-522-3800, 604...",[],bpower@sutton.com,http://www.sutton.com/sg/bpower,"{'facebook_url': None, 'twitter_url': None, 'l...",https://www.sutton.com/ca/agent/brian-power-61532
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5040,Mathieu,,Aubry inc.,groupe sutton - actuel inc.,Real Estate Broker,BIEN PLUS QUE DES PROMESSES...Ayant d'abord ob...,"[French, English]",https://www.sutton.com/storage/agents/api/1050...,"2975, Montee Saint-Hubert",St-Hubert,,Canada,J3Y4H6,[],[514-883-0284],maubry@sutton.com,,"{'facebook_url': None, 'twitter_url': None, 'l...",https://www.sutton.com/ca/agent/mathieu-aubry-...
5041,Susan,,Borinsky,"Sutton Group - Associates Realty Inc., Brokerage",Sales Representative,Susan Borinsky is a Sales Representative at Su...,"[English, French]",https://www.sutton.com/storage/agents/api/5522...,358 Davenport Road,Toronto,,Canada,M5R1K6,"[416-966-0300, 416-966-0080]",[],sborinsky@sutton.com,,"{'facebook_url': None, 'twitter_url': None, 'l...",https://www.sutton.com/ca/agent/susan-borinsky...
5042,Lacey,,Westcott,"Sutton Group - Quantum Realty Inc., Brokerage",Sales Representative,Lacey Westcott is a Sales Representative at Su...,[English],https://www.sutton.com/storage/agents/api/1227...,1673 Lakeshore Rd W,MISSISSAUGA,,Canada,L5J1J4,[416.856.7564],[],laceywestcott@sutton.com,,"{'facebook_url': None, 'twitter_url': None, 'l...",https://www.sutton.com/ca/agent/lacey-westcott...
5043,Cody,,Robinson,Sutton Group - West Coast Realty,Sales Representative,Cody Robinson is a Sales Representative at Sut...,[English],https://www.sutton.com/storage/agents/api/1099...,"PO Box 282, 655 School Road",Gibsons,,Canada,V0N1V0,[],[778-997-8844],crobinson@sutton.com,,"{'facebook_url': None, 'twitter_url': None, 'l...",https://www.sutton.com/ca/agent/cody-robinson-...
5044,Gary,,Dhanesar,Sutton Group - West Coast Realty,Sales Representative,Gary Dhanesar is a Sales Representative at Sut...,[English],https://www.sutton.com/storage/agents/api/9776...,15595 24th Avenue,Surrey,,Canada,V4P1H5,[604-572-3005],[604-773-7600],gdhanesar@sutton.com,,"{'facebook_url': None, 'twitter_url': None, 'l...",https://www.sutton.com/ca/agent/gary-dhanesar-...

In [17]:
df.to_json(r"/home/resmi/Downloads/sutton_2026_06_05 (1).json", orient='records', lines=True, index=False)

In [19]:
pd.read_json(r"/home/resmi/Downloads/sutton_2026_06_05 (1).json", lines=True)

,first_name,middle_name,last_name,office_name,title,description,languages,image_url,address,city,state,country,zipcode,office_phone_numbers,agent_phone_numbers,email,website,social,profile_url
0,Yenisleidis,,Infante Morales,groupe sutton - clodem inc.,Affiliated Real Estate Broker,Yenisleidis Infante Morales is a Affiliated Re...,"[French, Spanish]",https://www.sutton.com/storage/agents/api/1224...,9515 Boulevard LaSalle,LaSalle,QC,Canada,H8R2M9,[],[438-371-5960],yeni@sutton.com,https://www.facebook.com/yenisleidis.infantemo...,{'facebook_url': 'https://www.facebook.com/yen...,https://www.sutton.com/ca/agent/yenisleidis-in...
1,Ingrid,,Keen,"Sutton Group - Summit Realty Inc., Brokerage",Sales Representative,Ingrid Keen is a Sales Representative at Sutto...,[],https://www.sutton.com/storage/agents/api/5735...,33 Pearl Street,Mississauga,,Canada,L5M1X1,"[905-407-1828, 905-681-7900, 905-681-8225, 905...",[],ikeen@sutton.com,http://suttonsummit.ca,"{'facebook_url': None, 'twitter_url': None, 'l...",https://www.sutton.com/ca/agent/ingrid-keen-57352
2,Linda,,D'Eon,"Sutton Group - Quantum Realty Inc., Brokerage",Sales Representative,Linda D'Eon is a Sales Representative at Sutto...,[English],https://www.sutton.com/storage/agents/api/1045...,1673 Lakeshore Rd W,MISSISSAUGA,,Canada,L5J1J4,[416-305-5617],[],ldeon@sutton.com,,"{'facebook_url': None, 'twitter_url': None, 'l...",https://www.sutton.com/ca/agent/linda-d'eon-10...
3,Youngho,,Kim,Sutton Group - West Coast Realty,Personal Real Estate Corporation Licensing,Youngho Kim is a Sales Representative at Sutto...,[English],https://www.sutton.com/storage/agents/api/1220...,102 - 403 North Road,Coquitlam,BC,Canada,V3K3V9,[778-231-5329],[],ykim@sutton.com,,"{'facebook_url': None, 'twitter_url': None, 'l...",https://www.sutton.com/ca/agent/youngho-kim-12...
4,Brian,,Power,Sutton Group - West Coast Realty,Sales Representative,Brian Power is a Sales Representative at Sutto...,[English],https://www.sutton.com/storage/agents/api/6153...,102 - 403 North Road,Coquitlam,,Canada,V3K3V9,"[604-415-9800, 604-671-4393, 604-522-3800, 604...",[],bpower@sutton.com,http://www.sutton.com/sg/bpower,"{'facebook_url': None, 'twitter_url': None, 'l...",https://www.sutton.com/ca/agent/brian-power-61532
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5040,Mathieu,,Aubry inc.,groupe sutton - actuel inc.,Real Estate Broker,BIEN PLUS QUE DES PROMESSES...Ayant d'abord ob...,"[French, English]",https://www.sutton.com/storage/agents/api/1050...,"2975, Montee Saint-Hubert",St-Hubert,,Canada,J3Y4H6,[],[514-883-0284],maubry@sutton.com,,"{'facebook_url': None, 'twitter_url': None, 'l...",https://www.sutton.com/ca/agent/mathieu-aubry-...
5041,Susan,,Borinsky,"Sutton Group - Associates Realty Inc., Brokerage",Sales Representative,Susan Borinsky is a Sales Representative at Su...,"[English, French]",https://www.sutton.com/storage/agents/api/5522...,358 Davenport Road,Toronto,,Canada,M5R1K6,"[416-966-0300, 416-966-0080]",[],sborinsky@sutton.com,,"{'facebook_url': None, 'twitter_url': None, 'l...",https://www.sutton.com/ca/agent/susan-borinsky...
5042,Lacey,,Westcott,"Sutton Group - Quantum Realty Inc., Brokerage",Sales Representative,Lacey Westcott is a Sales Representative at Su...,[English],https://www.sutton.com/storage/agents/api/1227...,1673 Lakeshore Rd W,MISSISSAUGA,,Canada,L5J1J4,[416.856.7564],[],laceywestcott@sutton.com,,"{'facebook_url': None, 'twitter_url': None, 'l...",https://www.sutton.com/ca/agent/lacey-westcott...
5043,Cody,,Robinson,Sutton Group - West Coast Realty,Sales Representative,Cody Robinson is a Sales Representative at Sut...,[English],https://www.sutton.com/storage/agents/api/1099...,"PO Box 282, 655 School Road",Gibsons,,Canada,V0N1V0,[],[778-997-8844],crobinson@sutton.com,,"{'facebook_url': None, 'twitter_url': None, 'l...",https://www.sutton.com/ca/agent/cody-robinson-...
5044,Gary,,Dhanesar,Sutton Group - West Coast Realty,Sales Representative,Gary Dhanesar is a Sales Representative at Sut...,[English],https://www.sutton.com/storage/agents/api/9776...,15595 24th Avenue,Surrey,,Canada,V4P1H5,[604-572-3005],[604-773-7600],gdhanesar@sutton.com,,"{'facebook_url': None, 'twitter_url': None, 'l...",https://www.sutton.com/ca/agent/gary-dhanesar-...

In [21]:
df.to_excel(r"/home/resmi/Downloads/sutton_2026_06_05 (1).xlsx", index=False)

In [22]:
df.to_parquet(r"/home/resmi/Downloads/sutton_2026_06_05 (1).parquet", engine='pyarrow', index=False)